//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpdl1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NhomChiTieu
    {
        public long ID { get; set; }
        public string Ten { get; set; }
        public Nullable<long> PhiThuNghiem1 { get; set; }
        public Nullable<long> PhiThuNghiem2 { get; set; }
        public Nullable<long> PhiThuNghiem3 { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public bool HieuLuc { get; set; }
    }
}
