//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpdl1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TaiKhoan
    {
        public long ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Fullname { get; set; }
        public bool IsAdmin { get; set; }
        public bool HieuLuc { get; set; }
        public bool ChiTiepNhan { get; set; }
        public Nullable<long> QuyenSuDungID { get; set; }
        public Nullable<long> ToChucDoanTheID { get; set; }
        public Nullable<long> NhomID { get; set; }
        public string MaNhanSu { get; set; }
        public byte[] AnhNhanVien { get; set; }
        public bool DangKyNhapKhau { get; set; }
        public string PhanMem { get; set; }
        public Nullable<bool> TruongLaBo { get; set; }
        public Nullable<bool> MessageBoard { get; set; }
        public Nullable<bool> QuanTriOnline { get; set; }
        public Nullable<bool> KTNNCapSo { get; set; }
    
        public virtual DM_ToChucDoanTheNhom DM_ToChucDoanTheNhom { get; set; }
        public virtual NS_HoSo NS_HoSo { get; set; }
    }
}
