//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpdl1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_ToChucDoanTheNhom
    {
        public DM_ToChucDoanTheNhom()
        {
            this.DM_TaiKhoan = new HashSet<DM_TaiKhoan>();
        }
    
        public long ID { get; set; }
        public Nullable<short> STT { get; set; }
        public string MaNhom { get; set; }
        public string TenNhom { get; set; }
        public long ToChucDoanTheID { get; set; }
        public string DienThoai { get; set; }
    
        public virtual ICollection<DM_TaiKhoan> DM_TaiKhoan { get; set; }
        public virtual DM_ToChucDoanThe DM_ToChucDoanThe { get; set; }
    }
}
