//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpdl1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_HoSoKiemNghiem
    {
        public DT_HoSoKiemNghiem()
        {
            this.DT_MauKiemNghiem = new HashSet<DT_MauKiemNghiem>();
        }
    
        public long ID { get; set; }
        public string MaHoSo { get; set; }
        public long LoaiMauID { get; set; }
        public Nullable<long> NgayLapQLCL { get; set; }
        public long NgayLap { get; set; }
        public Nullable<long> NgayLayMau { get; set; }
        public string MaNhanSu { get; set; }
        public string TenKhachHang { get; set; }
        public string DienThoaiKhachHang { get; set; }
        public string DiaChiKhachHang { get; set; }
        public Nullable<long> KhachHangID { get; set; }
        public Nullable<long> KhachHangTACNID { get; set; }
        public string NguoiGuiMau { get; set; }
        public Nullable<long> PhanLoaiThucPhamID { get; set; }
        public Nullable<long> PhanLoaiThucPhamDichVuID { get; set; }
        public Nullable<long> QuyDinhKiemNghiemID { get; set; }
        public Nullable<long> DangKyNhapKhauID { get; set; }
        public Nullable<long> DangKyTACNID { get; set; }
        public Nullable<long> QuyetDinhThanhTraID { get; set; }
        public string SoDangKy { get; set; }
        public string SoHanhChinh { get; set; }
        public Nullable<long> NgayHanhChinh { get; set; }
        public string NguoiKyHanhChinh { get; set; }
        public Nullable<long> NgayHenTra { get; set; }
        public string GiayToKemTheo { get; set; }
        public string YeuCauKhac { get; set; }
        public string GhiChu { get; set; }
        public string GhiChuNoiBo { get; set; }
        public string GhiChuTruongLabo { get; set; }
        public string GhiChuKeToan { get; set; }
        public Nullable<long> NgayTra { get; set; }
        public string NoiDungTra { get; set; }
        public long TrangThaiID { get; set; }
        public Nullable<long> TrangThaiTempID { get; set; }
        public Nullable<short> SoNgayTraKetQua { get; set; }
        public Nullable<bool> DichVuNhanh { get; set; }
        public Nullable<long> QLCLXacNhan { get; set; }
        public Nullable<bool> QLCLBanGiao { get; set; }
        public Nullable<long> NgayQLCLBanGiao { get; set; }
        public Nullable<bool> KTKNXacNhan { get; set; }
        public Nullable<System.DateTime> NgayKTKNXacNhan { get; set; }
        public Nullable<bool> TACNXacNhan { get; set; }
        public Nullable<System.DateTime> NgayTACNXacNhan { get; set; }
        public long NgayTao { get; set; }
        public string UserTao { get; set; }
        public Nullable<long> NgaySua { get; set; }
        public string UserSua { get; set; }
        public Nullable<long> QLCLChiDinhID { get; set; }
    
        public virtual DM_LoaiMau DM_LoaiMau { get; set; }
        public virtual DM_TrangThai DM_TrangThai { get; set; }
        public virtual DT_DangKyNhapKhau DT_DangKyNhapKhau { get; set; }
        public virtual NS_HoSo NS_HoSo { get; set; }
        public virtual ICollection<DT_MauKiemNghiem> DT_MauKiemNghiem { get; set; }
    }
}
