//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpdl1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_MauKiemNghiem
    {
        public DT_MauKiemNghiem()
        {
            this.DT_PhieuPhanTich = new HashSet<DT_PhieuPhanTich>();
        }
    
        public long ID { get; set; }
        public Nullable<long> HoSoID { get; set; }
        public Nullable<long> BienBanThanhTraID { get; set; }
        public Nullable<long> MauKiemNghiemGopMauID { get; set; }
        public Nullable<long> PhanLoaiNguyenLieuID { get; set; }
        public string TenMau { get; set; }
        public string TenMauLabo { get; set; }
        public string MaSoMau { get; set; }
        public Nullable<double> TongSoMau { get; set; }
        public Nullable<double> SoMauLuu { get; set; }
        public Nullable<long> NgaySanXuat { get; set; }
        public string DinhDangNgaySanXuat { get; set; }
        public string SoLo { get; set; }
        public string QuyCachDongGoi { get; set; }
        public string DinhDangHanSuDung { get; set; }
        public Nullable<long> HanSuDung { get; set; }
        public string HanSuDungText { get; set; }
        public string TinhTrangMau { get; set; }
        public string NhietDoBaoQuan { get; set; }
        public string MoTaMau { get; set; }
        public Nullable<bool> PhieuKetQua { get; set; }
        public string SoHanhChinh { get; set; }
        public Nullable<long> NgayHanhChinh { get; set; }
        public Nullable<long> ThoiGianHanhChinh { get; set; }
        public string NguoiKyHanhChinh { get; set; }
        public string GhiChuHanhChinh { get; set; }
        public string DangSanPham { get; set; }
        public string NhanSanPham { get; set; }
        public string MauSac { get; set; }
        public string Mui { get; set; }
        public string KetLuan { get; set; }
        public Nullable<double> SoLuong1 { get; set; }
        public string DonViTinhSoLuong1 { get; set; }
        public string GhiChuSoLuong { get; set; }
        public Nullable<double> KhoiLuong1 { get; set; }
        public string DonViTinhKhoiLuong1 { get; set; }
        public string GhiChuKhoiLuong { get; set; }
        public byte[] TachPhieuKetQua { get; set; }
        public string TenCoSoNhaSanXuat { get; set; }
        public string DiaChiCoSoNhaSanXuat { get; set; }
        public Nullable<double> LuongMauKiemNghiem { get; set; }
        public string QuyCachNiemPhong { get; set; }
        public string DonViLuongMau { get; set; }
        public string GhiChuLuongMau { get; set; }
        public long NgayTao { get; set; }
        public string UserTao { get; set; }
        public Nullable<long> NgaySua { get; set; }
        public string UserSua { get; set; }
        public Nullable<short> SoLanLam { get; set; }
        public Nullable<long> DangKyNhapKhauDetailID { get; set; }
        public string CodeMau { get; set; }
        public string QLCLGhiChu { get; set; }
        public Nullable<bool> CamQuan { get; set; }
        public Nullable<bool> KhoaSoHanhChinh { get; set; }
    
        public virtual DT_HoSoKiemNghiem DT_HoSoKiemNghiem { get; set; }
        public virtual ICollection<DT_PhieuPhanTich> DT_PhieuPhanTich { get; set; }
    }
}
