//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpdl1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_PhieuPhanTichChiTieu
    {
        public long ID { get; set; }
        public long PhieuPhanTichID { get; set; }
        public long ChiTieuID { get; set; }
        public Nullable<long> NgayHenTra { get; set; }
        public string GhiChu { get; set; }
        public Nullable<long> NgayGiaoViec { get; set; }
        public string MaKiemNghiemVien { get; set; }
        public Nullable<bool> KhongPhatHien { get; set; }
        public string LOD { get; set; }
        public string KetQua { get; set; }
        public byte[] KetQuaRTF { get; set; }
        public Nullable<long> NgayKetQua { get; set; }
        public Nullable<long> PhuongPhapThuID { get; set; }
        public string PhuongPhapThu { get; set; }
        public string DanhGia { get; set; }
        public string DonViText { get; set; }
        public byte[] DonVi { get; set; }
        public Nullable<bool> KhoaKetQua { get; set; }
        public Nullable<bool> KhongPhatHien1 { get; set; }
        public string LOD1 { get; set; }
        public string KetQua1 { get; set; }
        public byte[] KetQuaRTF1 { get; set; }
        public Nullable<long> NgayKetQua1 { get; set; }
        public Nullable<long> PhuongPhapThuID1 { get; set; }
        public string PhuongPhapThu1 { get; set; }
        public string DanhGia1 { get; set; }
        public string DonViText1 { get; set; }
        public byte[] DonVi1 { get; set; }
        public Nullable<bool> XacNhanKetQua { get; set; }
        public Nullable<long> NgayXacNhanKetQua { get; set; }
        public long NgayTao { get; set; }
        public string UserTao { get; set; }
        public Nullable<long> NgaySua { get; set; }
        public string UserSua { get; set; }
        public string DonViCR { get; set; }
        public string DonViCR1 { get; set; }
        public string KetQuaCR { get; set; }
        public string KetQuaCR1 { get; set; }
        public Nullable<bool> Vilas { get; set; }
        public Nullable<bool> Vilas1 { get; set; }
        public Nullable<short> DinhTinhDinhLuong { get; set; }
        public string TenHoatChat { get; set; }
        public string TenHoatChat1 { get; set; }
        public Nullable<bool> ChoBoSung { get; set; }
        public Nullable<long> NgayXacNhanKetQuaBK { get; set; }
    
        public virtual DM_ChiTieu DM_ChiTieu { get; set; }
        public virtual DT_PhieuPhanTich DT_PhieuPhanTich { get; set; }
        public virtual NS_HoSo NS_HoSo { get; set; }
    }
}
