//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpdl1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_PhieuPhanTich
    {
        public DT_PhieuPhanTich()
        {
            this.DT_PhieuPhanTichChiTieu = new HashSet<DT_PhieuPhanTichChiTieu>();
        }
    
        public long ID { get; set; }
        public long NgayLap { get; set; }
        public Nullable<long> NgayKetQua { get; set; }
        public long MauID { get; set; }
        public long ToChucDoanTheID { get; set; }
        public double SoLuong { get; set; }
        public Nullable<long> NgayHenTra { get; set; }
        public Nullable<bool> ChiTieuDinhKem { get; set; }
        public string GhiChu { get; set; }
        public long NgayTao { get; set; }
        public string UserTao { get; set; }
        public Nullable<long> NgaySua { get; set; }
        public string UserSua { get; set; }
    
        public virtual DM_ToChucDoanThe DM_ToChucDoanThe { get; set; }
        public virtual DT_MauKiemNghiem DT_MauKiemNghiem { get; set; }
        public virtual ICollection<DT_PhieuPhanTichChiTieu> DT_PhieuPhanTichChiTieu { get; set; }
    }
}
