//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpdl1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class luanvanEntities : DbContext
    {
        public luanvanEntities()
            : base("name=luanvanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_ChiTieu> DM_ChiTieu { get; set; }
        public virtual DbSet<DM_LoaiMau> DM_LoaiMau { get; set; }
        public virtual DbSet<DM_NhomChiTieu> DM_NhomChiTieu { get; set; }
        public virtual DbSet<DM_TaiKhoan> DM_TaiKhoan { get; set; }
        public virtual DbSet<DM_ToChucDoanThe> DM_ToChucDoanThe { get; set; }
        public virtual DbSet<DM_ToChucDoanTheNhom> DM_ToChucDoanTheNhom { get; set; }
        public virtual DbSet<DM_TrangThai> DM_TrangThai { get; set; }
        public virtual DbSet<DT_DangKyNhapKhau> DT_DangKyNhapKhau { get; set; }
        public virtual DbSet<DT_HoSoKiemNghiem> DT_HoSoKiemNghiem { get; set; }
        public virtual DbSet<DT_MauKiemNghiem> DT_MauKiemNghiem { get; set; }
        public virtual DbSet<DT_PhieuPhanTich> DT_PhieuPhanTich { get; set; }
        public virtual DbSet<DT_PhieuPhanTichChiTieu> DT_PhieuPhanTichChiTieu { get; set; }
        public virtual DbSet<NS_HoSo> NS_HoSo { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
